### PR TITLE
Bumped up ruby version

### PR DESCRIPTION
**Pull request by frezbo**

### CODE REVIEW

**Comment by frezbo** [comment]
@someara can you please merge these changes?

**Comment by someara** [comment]
@sinfomicien ? Can we transfer this repo?

**Comment by frezbo** [comment]
@someara transfer to the official MySQL repo?

**Comment by someara** [comment]
Just a different org where the owner is responsive

**Comment by frezbo** [comment]
@someara  Who can pick it up?

**Comment by someara** [comment]
I certainly don't want it. The only reason I'm chiming in is because I have commit bit.

**Comment by frezbo** [comment]
@sinfomicien please provide a solution?

**Comment by tas50** [comment]
I'd love to get this one transferred to Sous Chefs. We have a team of active maintainers and process for people to come in / out and get work done regardless of an individual maintainer. http://sous-chefs.org/

**Comment by frezbo** [comment]
@tas50 cool, could you please do that ASAP, as when Chef 13 is released it would break many cookbooks

**Comment by tas50** [comment]
There's a few changes to make here, but this fixes enough that it's worth getting in

**Pull request merged**
